# Site settings
title: Kopf Lab
email: sebastian.kopf@colorado.edu
owner: Sebastian Kopf
description: > # this means to ignore newlines until "baseurl:"
  Stable Isotope Geomicrobiology Lab at the University of Colorado in Boulder
url: "http://kopflab.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
