# Site settings
owner: Sebastian Kopf
title: Kopf Lab
email: sebastian.kopf@colorado.edu
phone: +1.303.735.6207
github: KopfLab
twitter: kopf_lab
ga: UA-106138361-7
address: >
  Univ. of Colorado<br/>
  Department of Geol. Sciences<br/>
  2200 Colorado Ave<br/>
  UCB 399, Rm 285<br/>
  Boulder, CO 80309-0001
map_location: 2200 Colorado Ave, Boulder, CO 80309
map_label: Benson Earth Sciences, Colorado Avenue, Boulder, CO
description: >
  Geomicrobial Physiology Lab at the University of Colorado in Boulder
url: "https://kopflab.org"
urlencode: "https%3A%2F%2Fkopflab.org"
icon: "/images/header/cubes_sil.png"
permalink: /:categories/:title/
front_page_news: 5

# Build settings
markdown: kramdown

# Sitemap
plugins:
  - jekyll-sitemap
  - jekyll-gist

# Non-news data
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/
  people_team:
    output: true
    permalink: /people/:path/
  people_collaborators:
    output: true
    permalink: /people/:path/
  people_alumni:
    output: true
    permalink: /people/:path/
  resources_facilities:
    output: true
    permalink: /resources/:path/
  resources_equipment:
    output: true
    permalink: /resources/:path/
  resources_labware:
    output: true
    permalink: /resources/:path/
  resources_software:
    output: true
    permalink: /resources/:path/
