# Site settings
owner: Sebastian Kopf
title: Kopf Lab
email: sebastian.kopf@colorado.edu
phone: +1.303.735.6207
github: KopfLab
twitter: kopf_lab
address: >
  Univ. of Colorado<br/>
  Department of Geol. Sciences<br/>
  2200 Colorado Ave<br/>
  UCB 399, Rm 285<br/>
  Boulder, CO 80309-0001
map_location: 2200 Colorado Ave, Boulder, CO 80309
map_label: Benson Earth Sciences, Colorado Avenue, Boulder, CO
description: >
  Geomicrobial Physiology Lab at the University of Colorado in Boulder
url: "https://kopflab.org"
urlencode: "https%3A%2F%2Fkopflab.org"
icon: "/header_images/cubes_sil.png"
permalink: /:categories/:title/
front_page_news: 4

# Build settings
markdown: kramdown

# Sitemap
plugins:
  - jekyll-sitemap
  - jekyll-gist

# Non-news data
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /people/:path/
  collaborators:
    output: true
    permalink: /people/:path/
  alumni:
    output: true
    permalink: /people/:path/
